{
 "title": "Merca-Chain Performances Review",
 "description": "Overview of the most important Fabric, system and Docker container metrics. ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory Usage by all containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) - sum(container_memory_cache{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes - node_filesystem_free_bytes )/ node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Go Memory Allocations",
   "type": "graph",
   "description": "go_memstats_alloc_bytes",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Go Free Memory",
   "type": "graph",
   "description": "go_gc_duration_seconds",
   "gridPos": { "h": 11, "w": 8, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total[5m])",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"orderer\\\\.example\\\\.com:9443|peer0\\\\.org1\\\\.example\\\\.com:9444|peer0\\\\.org2\\\\.example\\\\.com:9445\"}"
    }
   ]
  },
  { "title": "Docker Containers Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (name)(rate(container_cpu_usage_seconds_total{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}[$interval])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"cadvisor|node-exporter|grafana|prometheus||\"} - container_memory_cache{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logging Rate per Container",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(logging_entries_checked{level=\"debug\"}[1m])"
    },
    {
     "expr": "rate(logging_entries_written{level=\"debug\"}[1m])"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (name)(rate(container_cpu_usage_seconds_total{name!~\"cadvisor|node-exporter|grafana|prometheus||\"}[$interval])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{name!~\"prometheus|cadvisor|grafana|node-exporter|\"}-container_memory_cache{name!~\"prometheus|cadvisor|grafana|node-exporter|\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!~\"prometheus|cadvisor|grafana|node-exporter\", name=~\".+\"} - container_memory_cache{name!~\"prometheus|cadvisor|grafana|node-exporter\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Chaincode Launch Duration",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chaincode_launch_duration_count",
     "legendFormat": "{{Count}}, {{chaincode}}"
    },
    { "expr": "chaincode_launch_duration_sum", "legendFormat": "{{Tota}}, {{chaincode}}" }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "description": "broadcast_enqueue_duration_sum",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job!=\"prometheus\"}[5m])",
     "legendFormat": "{{channel}}, {{job}}"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Endorser Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Successful Proposal Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel, chaincode) (rate(endorser_proposal_duration_sum{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval])) / sum without(channel, chaincode) (rate(endorser_proposal_duration_count{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proposal Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(endorser_proposals_received[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Proposals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(endorser_successful_proposals[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_block_processing_time_sum[$interval])) / sum without(channel) (rate(ledger_block_processing_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block  Storage Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_blockstorage_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_blockstorage_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_statedb_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_statedb_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blockchain height",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 89 },
   "targets": [
    { "expr": "ledger_blockchain_height", "legendFormat": "{{job}}" }
   ]
  }
 ]
}